management:
  endpoints:
    web:
      exposure:
        include: '*'
server:
  error:
    include-stacktrace: never
spring:
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
  security:
    user:
      name: user
      password: 123456

logging:
  level:
    org:
      springframework: info
      

      
